/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.paddy;

import org.paddy.machine.Enigma;
import org.paddy.machine.Rotor;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class App {
    static final String[] LETTERS = new String[]{"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
    public static final Set<String> LETTERSET = new HashSet<>(Arrays.asList(LETTERS));

    public static void main(String[] args) {
        if (args.length == 3) {
            final Rotor[] rotors = new Rotor[3];
            for (int i = 0; i < args.length; i++) {
                final String initialLetter = args[i];
                if (LETTERSET.contains(initialLetter)) {
                    rotors[i] = new Rotor(i, initialLetter);
                } else {
                    System.out.println("May only contain upper case letters of the alphabet!");
                    System.exit(0);
                }
            }
            final Enigma enigma = new Enigma(rotors);
            enigma.encrypt("ENIGMA");
            enigma.decrypt("GSPHDX");//DOG
            enigma.decrypt("QTRMGS");//CAT
        } else {
            System.out.println("Usage: ./gradlew run --args='X Y Z'");
        }
    }
}
