/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.paddy;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertThat(true).isTrue();
    }
}
